#!/usr/bin/env python3
# Edit a file in the host nvim instance.
import os
import sys

try:
    from neovim import attach
    addr = os.environ.get("NVIM_LISTEN_ADDRESS", None)
except:
    addr = False

if (not addr) or (len(sys.argv) != 2):
    os.execvp('man', sys.argv)

nvim = attach("socket", path=addr)

try:
    if (nvim.vars['shelley_noman'] == 1):
        raise Exception('g:shelley_noman is 1')
    nvim.command("Man " + sys.argv[1])
except:
    nvim.stop_loop()
    os.execvp('man', sys.argv)

nvim.stop_loop()
