#!/usr/bin/env python3
"""Cd nvim host instance"""
import os
import sys

try:
    from neovim import attach
    addr = os.environ.get("NVIM_LISTEN_ADDRESS", None)
except:
    addr = False

if (not addr) or (len(sys.argv) != 2):
    sys.exit(1)

nvim = attach("socket", path=addr)

try:
    # This will break if the path contains a quote
    # Solution: Don't use paths with quotes! ;)
    nvim.command("""if !exists("g:shelley_nocd") || g:shelley_nocd != 1
            let b:shelley_path = fnameescape('{}')
            exe "cd " . b:shelley_path
        fi\n""".format(sys.argv[1]))
finally:
    nvim.stop_loop()
