#!/usr/bin/env python3
import os
import sys

""" Cd nvim host instance """
def cd (addr, args):
	if (not addr) or (len(args) != 1):
		sys.exit(1)
	nvim = attach("socket", path=addr)
	try:
		# This will break if the path contains a quote
		# Solution: Don't use paths with quotes! ;)
		nvim.command("""if !(exists("g:shelley_nocd") && g:shelley_nocd == 1)
			let b:shelley_path = fnameescape('{}')
			exe "cd " . b:shelley_path
			fi\n""".format(args[0]))
	except:
		pass
	nvim.stop_loop()

""" Calls host instance's :Man """
def man (addr, args):
	if (not addr) or (len(args) != 1):
		os.execvp('man', ["man"] + args)
	nvim = attach("socket", path=addr)
	try:
		if (nvim.vars['shelley_noman'] == 1):
			raise Exception('g:shelley_noman is 1')
		nvim.command("Man " + args[0])
	except:
		nvim.stop_loop()
		os.execvp('man', ["man"] + args)
	nvim.stop_loop()

""" Calls host's precmd function """
def precmd (addr, args):
	if (not addr) or (len(args) != 1):
		exit()
	nvim = attach("socket", path=addr)
	try:
		nvim.command("""if !(exists("g:shelley_noprompt") && g:shelley_noprompt == 1)
			try
				call shelley#PreCmd({})
			entry
			endif\n""".format(args[0]))
	except:
		pass
	nvim.stop_loop()

""" Calls host's saveprompt function """
def saveprompt(addr, args):
	if (not addr) or (len(args) != 3):
		exit()
	nvim = attach("socket", path=addr)
	try:
		nvim.command("""if !(exists("g:shelley_noprompt") && g:shelley_noprompt == 1)
			try
				call shelley#SavePrompt({}, {}, '{}', {})
			endtry
			endif\n""".format(args[0], 1, args[1], args[2].count('\n')))
	except:
		pass
	nvim.stop_loop()

try:
    from neovim import attach
    addr = os.environ.get("NVIM_LISTEN_ADDRESS", None)
except:
    addr = False

functions = {"--cd": cd, "--man": man, "--precmd": precmd, "--saveprompt": saveprompt}
if (len(sys.argv) > 1) and (sys.argv[1] in functions):
	functions[sys.argv[1]](addr, sys.argv[2:])
