#!/usr/bin/env python3
import os
import sys

""" Calls host's precmd function """
def precmd (addr, args):
    nvim.command("""call shelley#PreCmd({})""".format(args[0]))

""" Calls host's preexec function """
def preexec(addr, args):
    nvim.command("""call shelley#PreExec({}, '{}', {})""".format(args[0], args[1], args[2].count('\n')))

try:
    from neovim import attach
    addr = os.environ.get("NVIM_LISTEN_ADDRESS", None)
    nvim = attach("socket", path=addr)
    try:
        functions = {"--precmd": precmd, "--preexec": preexec}
        if (len(sys.argv) > 1) and (sys.argv[1] in functions):
            functions[sys.argv[1]](addr, sys.argv[2:])
    except:
        pass
    finally:
        nvim.stop_loop()
except:
    pass
